package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Project13_Project131'
in the project with id = 'Project13', and delete the patch script.
*/
create(RelativeId("Project13"), Project({
    id("Project13_Project131")
    name = "project131"
}))

